before_script:
  - if [ -d "/home/ahmad/SonarProjects/hello-node" ]; then echo 'Existing'; else cp -R /home/ahmad/SonarProjects/examples /home/ahmad/SonarProjects/hello-node; fi
  - if [ -d "/home/ahmad/SonarProjects/hello-node" ]; then sed -i '1s/.*/sonar.projectKey=org.sonarqube:ahmad-hello-node/' /home/ahmad/SonarProjects/hello-node/sonar-project.properties; fi
  - if [ -d "/home/ahmad/SonarProjects/hello-node" ]; then sed -i '2s/.*/sonar.projectName=Ahmad Hello Node/' /home/ahmad/SonarProjects/hello-node/sonar-project.properties; fi
  - if [ -d "/home/ahmad/SonarProjects/hello-node/src/app" ]; then git pull origin master; else cd /home/ahmad/SonarProjects/hello-node/src && git clone https://ahmad:ardiansyah@repo.carsworld.id/ahmad/hello-node.git app; fi

stages:
  - build
  #- upload
  #- remove
  #- test
  #- deploy
  #- autotest

build_project:
  stage: build
  only:
    - master
  tags:
    #- dockerindependent
    - sonarqube
  script:
    #- docker build -t registry.carsworld.id/ahmad/hello-node:buildlocal .
    #- cd /home/ahmad/SonarProjects/hello-node && git pull origin master
    #- /home/ahmad/PhpProjects/test01/vendor/bin/phpunit /home/ahmad/PhpProjects/test01/DependTest.php
    - cd /home/ahmad/SonarProjects/hello-node && sonar-scanner -D sonar.login=f5da1de8b5c1f149fc0b4970ac58dbdb6b88522f

#upload_project:
  #stage: upload
  #only:
    #- master
  #tags:
    #- dockerindependent
  #script:
    #- docker push registry.carsworld.id/ahmad/hello-node:buildlocal

#remove_project:
  #stage: remove
  #only:
    #- master
  #tags:
    #- dockerindependent
  #script:
    #- docker rmi registry.carsworld.id/ahmad/hello-node:buildlocal

#test_project:
  #stage: test
  #only:
    #- master
  #tags:
    #- dockerindependent
  #script:
    #- docker run --name test_hello_node -dit registry.carsworld.id/ahmad/hello-node:buildlocal sh

#deploy_project:
  #stage: deploy
  #only:
    #- master
  #tags:
    #- dockerindependent
  #when: manual
  #script:
    #- docker run --name ahmad_hello_node -dit -p 8881:3000 registry.carsworld.id/ahmad/hello-node:buildlocal sh

#autotest_project:
  #stage: autotest
  #only:
    #- master
  #tags:
    #- windows
  #when: manual
  #script:
    #- set foldername=%date:~6,4%%date:~0,2%%date:~3,2%_%time:~0,2%24%time:~3,2%%time:~6,2%
    #- mkdir C:\Users\user\Katalon Studio\IWS_Admin\Reports\Test Suite\%foldername%
    #- katalon -noSplash  -runMode=console -consoleLog -projectPath="C:\Users\user\Katalon Studio\IWS_Admin\IWS_Admin.prj" -retry=0 -testSuitePath="Test Suites/Test Suite" -executionProfile="default" -browserType="Firefox" -summaryReport -reportFolder="C:\Users\user\Katalon Studio\IWS_Admin\Reports\Test Suite\%foldername%"