stages:
  - build
  - deploy

build_development:
  stage: build
  only:
    - development
  tags:
    - cw_dev_docker
  script:
    - echo "Build..."
    - docker rm -f dev_hello_node
    - docker rmi -f dev/hello-node:latest
    - docker build -t dev/hello-node:latest .
    - echo "Done..."

deploy_development:
  stage: deploy
  only:
    - development
  tags:
    - cw_dev_docker
  script:
    - echo "Deploy..."
    - docker run -dit --name dev_hello_node -p 3000:3000 dev/hello-node:latest
    - echo "Done..."

build_staging:
  stage: build
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Build..."
    - docker rm -f stg_hello_node
    - docker rmi -f stg/hello-node:latest
    - docker build -t stg/hello-node:latest .
    - echo "Done..."

deploy_staging:
  stage: deploy
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Deploy..."
    - docker run -dit --name stg_hello_node -p 3000:3000 stg/hello-node:latest
    - echo "Done..."
