stages:
  - build
  - deploy

build_app:
  stage: build
  only:
    - master
  tags:
    - builder01
  script:
    - echo "Build..."
    - docker build -t 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest .
    - docker push 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest
    - docker rmi -f 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest
    - echo "Done..."

deploy_app:
  stage: deploy
  only:
    - master
  tags:
    - prod_as_manager
  script:
    - echo "Deploy..."
    - if [ "$(docker stack ls | grep ahmad-stack)" ]; then 
        echo "Stack Exists"; 
        docker service update --force --image 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest ahmad-stack_microservis;
      else
        echo "Stack Not Exists";
        docker stack deploy --with-registry-auth -c docker-compose.yml ahmad-stack;
      fi
    - echo "Done..."
