stages:
  - build
  - upload
  - test
  - deploy

build_project:
  stage: build
  only:
    - master
  tags:
    - dockerindependent
  script:
    - docker build -t registry.carsworld.id/ahmad/hello-node:buildlocal .

upload_project:
  stage: upload
  only:
    - master
  tags:
    - dockerindependent
  script:
    - docker push registry.carsworld.id/ahmad/hello-node:buildlocal

test_project:
  stage: test
  only:
    - master
  tags:
    - dockerindependent
  script:
    - docker run --name test_hello_node -dit registry.carsworld.id/ahmad/hello-node:buildlocal npm test
    - docker logs test_hello_node

deploy_project:
  stage: deploy
  only:
    - master
  tags:
    - dockerindependent
  when: manual
  script:
    - docker run --name ahmad_hello_node -dit -p 8880:3000 registry.carsworld.id/ahmad/hello-node:buildlocal npm start
