stages:
  - build
  - deploy

build_staging:
  stage: build
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Build..."
    - if [ "$(docker ps -a | grep stg_hello_node)" ]; then
        echo "Container Exists";
        docker rm -f stg_hello_node;
        docker rmi -f stg/hello-node:latest;
      else
        echo "Container Not Found";
      fi
    - docker build -t stg/hello-node:latest .
    - echo "Done..."

deploy_staging:
  stage: deploy
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Deploy..."
    - docker run -dit --name stg_hello_node -p 3010:3000 stg/hello-node:latest
    - echo "Done..."
