stages:
  - build
  - deploy

build_development:
  stage: build
  only:
    - development
  tags:
    - cw_dev_docker
  script:
    - echo "Build..."
    - docker rm -f dev_hello_node
    - docker rmi -f dev/hello-node:latest
    - docker build -t dev/hello-node:latest .
    - echo "Done..."

deploy_development:
  stage: deploy
  only:
    - development
  tags:
    - cw_dev_docker
  script:
    - echo "Deploy..."
    - docker run -dit --name dev_hello_node -p 3333:3000 dev/hello-node:latest
    - echo "Done..."

build_staging:
  stage: build
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Build..."
    - docker rm -f stg_hello_node
    - docker rmi -f stg/hello-node:latest
    - docker build -t stg/hello-node:latest .
    - echo "Done..."

deploy_staging:
  stage: deploy
  only:
    - staging
  tags:
    - cw_stg_docker
  script:
    - echo "Deploy..."
    - docker run -dit --name stg_hello_node -p 3000:3000 stg/hello-node:latest
    - echo "Done..."

build_production:
  stage: build
  only:
    - master
  tags:
    - builder01
  script:
    - echo "Deploy"
    - aws ecr get-login --region ap-southeast-1 --no-include-email | sh
    - docker build -t 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest .
    - docker push 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest
    - docker rmi -f 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ms-aftersal/iws-mitra:latest
    - echo "Done..."


deploy_production:
  stage: deploy
  only:
    - master
  tags:
    - cw_prod_as_manager
  script:
    - echo "Deploy"
    - aws ecr get-login --region ap-southeast-1 --no-include-email | sh
    - if [ "$(docker stack ls | grep ms-ahmad-node-v1)" ]; then 
        echo "Stack Exists"; 
        docker service update --force --with-registry-auth --image 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ms-aftersal/iws-mitra:latest ms-ahmad-node-v1_microservis;
      else
        echo "Stack Not Exists";
        docker stack deploy --with-registry-auth -c docker-compose.yml ms-ahmad-node-v1;
      fi
    - echo "Done..."

