stages:
  - build
  - deploy

build_app:
  stage: build
  only:
    - master
  tags:
    - stgasman
  script:
    - echo "Build..."
    #- if [ ! "$(docker ps -q -f name=ahmad_hello_node)" ]; then echo "Container empty"; else docker rm -f ahmad_hello_node && docker rmi -f registry.carsworld.id/ahmad/hello-node:buildlocal; fi
    #- docker build -t registry.carsworld.id/ahmad/hello-node:buildlocal .
    #- docker push registry.carsworld.id/ahmad/hello-node:buildlocal

deploy_app:
  stage: deploy
  only:
    - master
  tags:
    - stgasman
  script:
    - if [ ! "$(docker stack ls | grep ahmad-stack)" ]; then 
        echo "Stack Exists"; 
      else
        echo "Stack Not Exists";
      fi
    #- docker run --name ahmad_hello_node -dit -p 9910:3000 registry.carsworld.id/ahmad/hello-node:buildlocal
    - echo "Done..."
