stages:
  - build
  - deploy

build_app:
  stage: build
  only:
    - master
  tags:
    - dockerbuilder
  script:
    - echo "Build..."
    - if [ "$(docker images -q registry.carsworld.id/ahmad/hello-node:buildlocal)" ]; then 
        echo "Image Exists"; 
        docker rmi -f registry.carsworld.id/ahmad/hello-node:buildlocal; 
      else 
        echo "Image Not Exists";
      fi
    - docker build -t registry.carsworld.id/ahmad/hello-node:buildlocal .
    - docker push registry.carsworld.id/ahmad/hello-node:buildlocal
    - echo "Done..."

deploy_app:
  stage: deploy
  only:
    - master
  tags:
    - stgasman
  script:
    - echo "Deploy..."
    - if [ "$(docker stack ls | grep ahmad-stack)" ]; then 
        echo "Stack Exists"; 
        docker service update --force --image registry.carsworld.id/ahmad/hello-node:buildlocal ahmad-stack_microservis;
      else
        echo "Stack Not Exists";
        docker stack deploy --with-registry-auth -c docker-compose.yml ahmad-stack;
      fi
    - echo "Done..."
