version: "3"
services:
  microservis:
    image: 228525134900.dkr.ecr.ap-southeast-1.amazonaws.com/ahmad/hello-node:latest
    ports:
      - "3120:3000"
    deploy:
      labels:
        - "swarm.autoscaler=true"
        - "swarm.autoscaler.minimum=2"
        - "swarm.autoscaler.maximum=6"
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
      - microservis
networks:
  microservis: